/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardTemplatesRouteRouteImport } from './routes/dashboard/templates/route'
import { Route as DashboardTemplatesIndexRouteImport } from './routes/dashboard/templates/index'
import { Route as DashboardTemplatesTemplateIdIndexRouteImport } from './routes/dashboard/templates/$templateId/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTemplatesRouteRoute = DashboardTemplatesRouteRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTemplatesIndexRoute = DashboardTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTemplatesRouteRoute,
} as any)
const DashboardTemplatesTemplateIdIndexRoute =
  DashboardTemplatesTemplateIdIndexRouteImport.update({
    id: '/$templateId/',
    path: '/$templateId/',
    getParentRoute: () => DashboardTemplatesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/templates': typeof DashboardTemplatesRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
  '/dashboard/templates/$templateId': typeof DashboardTemplatesTemplateIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/templates': typeof DashboardTemplatesIndexRoute
  '/dashboard/templates/$templateId': typeof DashboardTemplatesTemplateIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/templates': typeof DashboardTemplatesRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
  '/dashboard/templates/$templateId/': typeof DashboardTemplatesTemplateIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/templates'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/'
    | '/dashboard/templates/'
    | '/dashboard/templates/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard'
    | '/dashboard/templates'
    | '/dashboard/templates/$templateId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/templates'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/'
    | '/dashboard/templates/'
    | '/dashboard/templates/$templateId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/templates/': {
      id: '/dashboard/templates/'
      path: '/'
      fullPath: '/dashboard/templates/'
      preLoaderRoute: typeof DashboardTemplatesIndexRouteImport
      parentRoute: typeof DashboardTemplatesRouteRoute
    }
    '/dashboard/templates/$templateId/': {
      id: '/dashboard/templates/$templateId/'
      path: '/$templateId'
      fullPath: '/dashboard/templates/$templateId'
      preLoaderRoute: typeof DashboardTemplatesTemplateIdIndexRouteImport
      parentRoute: typeof DashboardTemplatesRouteRoute
    }
  }
}

interface DashboardTemplatesRouteRouteChildren {
  DashboardTemplatesIndexRoute: typeof DashboardTemplatesIndexRoute
  DashboardTemplatesTemplateIdIndexRoute: typeof DashboardTemplatesTemplateIdIndexRoute
}

const DashboardTemplatesRouteRouteChildren: DashboardTemplatesRouteRouteChildren =
  {
    DashboardTemplatesIndexRoute: DashboardTemplatesIndexRoute,
    DashboardTemplatesTemplateIdIndexRoute:
      DashboardTemplatesTemplateIdIndexRoute,
  }

const DashboardTemplatesRouteRouteWithChildren =
  DashboardTemplatesRouteRoute._addFileChildren(
    DashboardTemplatesRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardTemplatesRouteRoute: typeof DashboardTemplatesRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardTemplatesRouteRoute: DashboardTemplatesRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
